### ISSUE TITLE
Misbehaving URL

### ISSUE THREAD

**Issue by brousch** [mitechie/python-webpage-inliner#1]
When I try to fetch this URL through webinliner it comes back with an error page for an unknown location. My guess is something in the parameters is getting messed up.

http://forecast.weather.gov/afm/PointClick.php?lat=42.67190&lon=-85.64140

**Comment by mitechie** [comment]
You have to put the url into "" when there are things that the shell might accept as bash-isms in there. When I do that it works except for the fact that the website uses background images in the linked css files and the inline doesn't currently fetch those files as well. I'm not sure if you can inline them as you can the .css and other image files themselves.
